sudo: required
services:
  - docker

before_install: 
  - docker build -t filiocus/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true filiocus/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-637423331197"
  path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"